### ISSUE TITLE
Doesn't build when checking out

### ISSUE THREAD

**Issue by tympaniplayer** [Solaris-Skunk-Werks/battletech-force-balancer#1]
Hi there, a couple things. This doesn't build when I open it with netbeans and update the jdk version to 12. I am a .net dev so I realize I may be doing some things wrong because I'm not a java dev. I also am wondering if this is the most updated version? The GUI looks different than the one that ships with SSW from the website. There are a couple fixes I'd like to make.

**Comment by WEKarnesky** [comment]
Hey @tympaniplayer Is this still and outstanding issue?

**Comment by WEKarnesky** [comment]
Built and ran c06d963 from a fresh pull, I believe this issue is resolved.

**Comment by tympaniplayer** [comment]
OK cool. I think I must be too much of a Java noob. Thanks for checking.

**Comment by Algebro7** [comment]
There were a number of issues in the source tree that caused the project not to compile, so it wasn't your fault. I've just pushed some commits that allow the project to successfully build. There is also an experimental release now containing a prebuilt jar if you want to use that.

**Comment by tympaniplayer** [comment]
Great thanks! I'll take a look this weekend!

**Comment by WEKarnesky** [comment]
@tympaniplayer We also created a discord for SSW that you are welcome to join with this invite code: https://discordapp.com/invite/xc5pUWP
